// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPc7FHoS7N23o6QwsKmKNgiiO6I4oTgY',
    appId: '1:480874978209:web:9dd50ee2f379e9451789e0',
    messagingSenderId: '480874978209',
    projectId: 'new-chat-ac8b2',
    authDomain: 'new-chat-ac8b2.firebaseapp.com',
    storageBucket: 'new-chat-ac8b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfewfkPDSzk37kQeCEYBte1vyXgjmEyX0',
    appId: '1:480874978209:android:9e5df374755e285b1789e0',
    messagingSenderId: '480874978209',
    projectId: 'new-chat-ac8b2',
    storageBucket: 'new-chat-ac8b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36sAtEvBqp6t8dSSflXTRvtztfquxY9E',
    appId: '1:480874978209:ios:c74c4a12120fc2511789e0',
    messagingSenderId: '480874978209',
    projectId: 'new-chat-ac8b2',
    storageBucket: 'new-chat-ac8b2.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC36sAtEvBqp6t8dSSflXTRvtztfquxY9E',
    appId: '1:480874978209:ios:8e18f7a7e3ce880f1789e0',
    messagingSenderId: '480874978209',
    projectId: 'new-chat-ac8b2',
    storageBucket: 'new-chat-ac8b2.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
